-- Allow the frontend to supply an explicit petition identifier (8-digit numeric id).
-- The portal generates IDs client-side (used across links and subsequent submissions).
-- `GENERATED BY DEFAULT` preserves identity behavior when id is omitted, but permits explicit values.

ALTER TABLE public.project
  ALTER COLUMN id SET GENERATED BY DEFAULT;

